### ISSUE TITLE
Something about blob confused me.

### ISSUE THREAD

**Issue by gaow0007** [antran89/New-C3D-Caffe#2]
I find that you didn't modify the blob related code, and on my machine(windows8.1 + vs2013), the code occurs the`check failed num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.`. After I read the caffe source code,  I find that it result from blob.cpp and blob.hpp. I want to know that how you solve it.By the way, if you can offer some simple prototype examples about C3D, it will be better.

**Comment by antran89** [comment]
@SaberArthurus Thank for the feedback. I follow Caffe developer's principle, do not modify legacy codes unless it is necessary. I just modify only parts that makes program working, but not all the source codes.
Best regards,
