### ISSUE TITLE
Problems with Pool3DLayer

### ISSUE THREAD

**Issue by LuisTbx** [antran89/New-C3D-Caffe#3]
Hi, i was trying to pass the tests and found out there is a little bug: in pool3d_layer.hpp 
line
virtual inline const char\* type() const { return "POOLING3D"; }

Which should be change to:
virtual inline const char\* type() const { return "Pooling3D"; }

Cheers

**Comment by xiaoyuliu** [comment]
@LuisTbx Hi, can you please provide me a train_val.prototxt file?
I have no idea how to extract c3d features using this New-C3D-Caffe layers.

Thanks.

**Comment by LuisTbx** [comment]
Hi, I did not manage to pass all the test, and could not use the video layer. Thus, instead of fixing them, I decided to use another version by chuckcho called video-caffe.

https://github.com/chuckcho/video-caffe

Sorry for not being able to help.

Cheers,

**Comment by xiaoyuliu** [comment]
@LuisTbx No problem, thanks for the another version!

Best.

**Comment by antran89** [comment]
@LuisTbx Thank you for providing the feedback. I am sorry, I cannot support the repo. Hope you have found the code to work on.
Best regards,
