### ISSUE TITLE
redefinition of 'Backward_gpu' error

### ISSUE THREAD

**Issue by kimde** [antran89/New-C3D-Caffe#5]
Hi, I'm stuck in compilation problem with my Mac(OSX 10.12, CUDA 7.5).

When I try to build source with 'make all', there are " redefinition of 'Backward_gpu' " errors related with video_data_layer.cpp.

I think this is because I want to build CPU only mode..

How can I solve this problem? Thx in advance.

![2017-01-03 5 37 12](https://cloud.githubusercontent.com/assets/24889624/21602810/4e7f3a76-d1db-11e6-9dfb-d293f84bb2f7.png)

**Comment by antran89** [comment]
Hi @kimde,

Currently, I do not support to CPU_ONLY mode. It is recommended to use C3D with expensive 3D-conv in GPU mode. 

Thanks,
